= Bathe JSPC Compiler for Jetty

This assumes the use of web fragments and properly constructs them for JSPs. The standard jsp compiler for Jetty
does not support web fragments, this one *only* supports web fragments.

It will by default *delete* the jsps from your jar file to ensure that there is no possibility of your application
working on a JVM and then you deploying on a JRE and them not working (as there is no compiler). Be wary of this
if you rely on your jsps existing.

[source,xml]
----
<plugin>
  <groupId>com.bluetrainsoftware.bathe.web</groupId>
  <artifactId>bathe-jetty-jspc-maven-plugin</artifactId>
  <version>1.3</version>
  <dependencies>
	  <dependency>
		  <groupId>org.eclipse.jetty</groupId>
		  <artifactId>jetty-util</artifactId>
		  <version>${jetty.version}</version>
		  <scope>provided</scope>
	  </dependency>
	  <dependency>
		  <groupId>org.eclipse.jetty</groupId>
		  <artifactId>jetty-jsp</artifactId>
		  <version>${jetty-jsp.version}</version>
		  <scope>provided</scope>
	  </dependency>
  </dependencies>
  <executions>
    <execution>
        <id>war-compile-jsp</id>
        <goals>
          <goal>jspc</goal>
        </goals>
        <phase>compile</phase>
        <configuration>
            <compilerSourceVM>1.8</compilerSourceVM>
            <compilerTargetVM>1.8</compilerTargetVM>
        </configuration>
    </execution>
  </executions>
</plugin>

----

It is a bit icky because it dictates the version of Jetty and requires re-release for a new version. Generally that
isn't too much of a problem as the jsp layer doesn't change between versions of Jetty.

== Changelog

- 1.6 - you must now include your own version of the jetty libraries, they are provided now.
- 1.5 - update to allow using a later language release. Warning, I no longer use Jetty, so this isn't getting
much love.
